User.destroy_all
Outfit.destroy_all
Clothe.destroy_all

# one = Clothe.create(name: "V-Neck" , category: "Shirts", color: "Red")
# two = Clothe.create(name: "Little Black Dress" , category: "Dress", color: "Black")
# three = Clothe.create(name: "Superhero" , category: "Latex Suit", color: "Red")
# four = Clothe.create(name: "Boy's Dress" , category: "Dress", color: "Blue")
# five = Clothe.create(name: "Leather Gloves" , category: "Accessories", color: "Red")
# six = Clothe.create(name: "Heels" , category: "Footwear", color: "Yellow")
# seven = Clothe.create(name: "Sun Hat" , category: "Accessories", color: "Orange")
# eight = Clothe.create(name: "Joggers" , category: "Pants", color: "Green")
# nine = Clothe.create(name: "Button-Down" , category: "Shirts", color: "White")
# ten = Clothe.create(name: "Converse" , category: "Footwear", color: "White")

user_1 = User.create(username: "mikeycuts48", password: "fluffyanimals", bio: "I really like fluffy animals dressed up in cute outfits", display_name: "Mike Carlos")
user_2 = User.create(username: "gg_gina", password: "um", bio: "I don't know what to put here", display_name: "Gina Lee")
user_3 = User.create(username: "christopher_robin", password: "pooh", bio: "I'm a little boy who likes to wear dresses", display_name: "Chris Robin")
user_4 = User.create(username: "red_power_ranger", password: "red", bio: "Kick Ass", display_name: "Mr. Red")

############# SHIRTS ###############
Clothe.create(name:"Army Green Shirt", category:"Shirt", url:"shirts/army-green-shirt.jpg")
Clothe.create(name:"Blue Plaid", category:"Shirt", url:"shirts/blue-plaid.jpg")
Clothe.create(name:"Checkered Shirt", category:"Shirt", url:"shirts/checkered-shirt.jpeg")
Clothe.create(name:"Fitted Blue Button Up", category:"Shirt", url:"shirts/fitted-blue-button-up.jpg")
Clothe.create(name:"Fitted Pink Button Up", category:"Shirt", url:"shirts/fitted-pink-button-up.jpg")
white_button_up = Clothe.create(name:"Fitted White Button Up", category:"Shirt", url:"shirts/fitted-white-button-up.jpg")
gucci_rose = Clothe.create(name:"Gucci Rose Hoodie", category:"Shirt", url:"shirts/gucci-rose-hoodie.jpeg")
Clothe.create(name:"Stranger Things Hoodie", category:"Shirt", url:"shirts/gucci-stranger-things-hoodie.png")
Clothe.create(name:"Long Baseball Tee", category:"Shirt", url:"shirts/long-baseball-tee.png")
Clothe.create(name:"Octocat Shirt", category:"Shirt", url:"shirts/octocat-shirt.png")
Clothe.create(name:"Orange Hoodie", category:"Shirt", url:"shirts/orange-hoodie.jpg")
pug_life = Clothe.create(name:"Pug Life Shirt", category:"Shirt", url:"shirts/pug-life-shirt.jpg")
Clothe.create(name:"Pug Shirt", category:"Shirt", url:"shirts/pug-shirt.jpg")
pugtato = Clothe.create(name:"Pugtato Shirt", category:"Shirt", url:"shirts/pugtato-shirt.jpg")
Clothe.create(name:"The Office Shirt", category:"Shirt", url:"shirts/the-office-aqua-blue-shirt.png")

############# PANTS ###############
shorts = Clothe.create(name:"Black Shorts", category:"Pants", url:"pants/black-shorts.jpg")
belt_skirt = Clothe.create(name:"Black Skirt With Belt", category:"Pants", url:"pants/black-skirt-belt.jpeg")
Clothe.create(name:"Black Skirt", category:"Pants", url:"pants/black-skirt.jpg")
plaid_skirt = Clothe.create(name:"Blue/Green Plaid Skirt", category:"Pants", url:"pants/blue-green-plaid-skirt.jpeg")
Clothe.create(name:"Brick Pants", category:"Pants", url:"pants/brick-pants.jpg")
Clothe.create(name:"Dripping Space", category:"Pants", url:"pants/dripping-space-sweatpants.jpg")
Clothe.create(name:"Grey Sweatshorts", category:"Pants", url:"pants/grey-sweatshorts.png")
Clothe.create(name:"Gray Straight Pant", category:"Pants", url:"pants/grey-straight-pant.jpg")
Clothe.create(name:"Gray Sweatpants", category:"Pants", url:"pants/grey-sweatpants.jpg")
Clothe.create(name:"Hundred Sweatpants", category:"Pants", url:"pants/hundred-sweatpants.jpg")
khaki_cuff = Clothe.create(name:"Khaki Cuff Joggers", category:"Pants", url:"pants/khaki-cuff-joggers.jpg")
Clothe.create(name:"Light Blue Jeans", category:"Pants", url:"pants/light-blue-jeans.jpg")
Clothe.create(name:"Light Pink Shorts", category:"Pants", url:"pants/light-pink-shorts.jpg")
Clothe.create(name:"Long Red Skirt", category:"Pants", url:"pants/long-red-skirt.jpg")
Clothe.create(name:"Mens Leggings", category:"Pants", url:"pants/mens-leggings.jpg")
Clothe.create(name:"Navy Blue Ruffle Skirt", category:"Pants", url:"pants/navy-blue-ruffle-skirt.jpeg")
Clothe.create(name:"Navy Blue Skirt", category:"Pants", url:"pants/navy-blue-skirt.jpeg")
Clothe.create(name:"Neon Blue Shorts", category:"Pants", url:"pants/neon-blue-shorts.jpg")
Clothe.create(name:"Olive Green Pants", category:"Pants", url:"pants/olive-green-pant.jpg")
Clothe.create(name:"Olive Khaki Pants", category:"Pants", url:"pants/olive-khaki-pants.jpg")
Clothe.create(name:"Powered By Plants Sweatpants", category:"Pants", url:"pants/powered-by-plants-sweatpants.png")
Clothe.create(name:"Red Spiral Long Skirt", category:"Pants", url:"pants/red-spiral-long-skirt.jpg")
Clothe.create(name:"Rooster Sweatpants", category:"Pants", url:"pants/rooster-sweatpants.png")
Clothe.create(name:"Sky Blue Sweatshorts", category:"Pants", url:"pants/sky-blue-sweatshorts.jpg")
Clothe.create(name:"Tan Skirt", category:"Pants", url:"pants/tan-skirt.jpg")
Clothe.create(name:"Wheat Pants", category:"Pants", url:"pants/wheat-pants.jpg")
Clothe.create(name:"Womens Dark Jean Shorts", category:"Pants", url:"pants/womens-dark-jean-shorts.jpg")
Clothe.create(name:"Womens Grey Leggings", category:"Pants", url:"pants/womens-grey-leggings.jpg")
Clothe.create(name:"Yellow Plais Skirt", category:"Pants", url:"pants/yellow-plaid-skirt.png")

############# PANTS ###############
dress_shoes = Clothe.create(name:"Black Dress Shoes", category:"Footwear", url:"footwear/black-dress-shoes.jpg")
Clothe.create(name:"Black Heels", category:"Footwear", url:"footwear/black-heels.jpg")
Clothe.create(name:"Black Open Heels", category:"Footwear", url:"footwear/black-open-heels.jpg")
Clothe.create(name:"Black Suede Shoes", category:"Footwear", url:"footwear/black-suede-shoes.jpg")
Clothe.create(name:"Blue Green Converse", category:"Footwear", url:"footwear/blue-green-converse.jpg")
Clothe.create(name:"Blue Puma", category:"Footwear", url:"footwear/blue-puma.jpg")
Clothe.create(name:"Brown Dress Shoes", category:"Footwear", url:"footwear/brown-dress-shoes.jpg")
Clothe.create(name:"Brown Shoes", category:"Footwear", url:"footwear/brown-shoes.jpg")
docs = Clothe.create(name:"Doc Martens Shoes", category:"Footwear", url:"footwear/doc-marten-shoes.jpg")
Clothe.create(name:"Doc Martens Boots", category:"Footwear", url:"footwear/doc-martens-boots.png")
Clothe.create(name:"Doc Martens Flower Boots", category:"Footwear", url:"footwear/doc-martens-flower-boots.jpeg")
long_docs = Clothe.create(name:"Doc Martens Long Boots", category:"Footwear", url:"footwear/doc-martens-long-boots.jpg")
Clothe.create(name:"Jordan Heels", category:"Footwear", url:"footwear/jordan-heels.jpg")
Clothe.create(name:"Nike Sneakers", category:"Footwear", url:"footwear/nike-sneakers.jpg")
Clothe.create(name:"Red Converse", category:"Footwear", url:"footwear/red-converse.jpg")
Clothe.create(name:"White Blue Black Sneakers", category:"Footwear", url:"footwear/white-blue-black-sneakers.jpg")
adidas = Clothe.create(name:"Adidas Black Stripe", category:"Footwear", url:"footwear/adidas-black-stripe.jpg")
Clothe.create(name:"Teal Sneakers", category:"Footwear", url:"footwear/teal-sneakers.jpg")
Clothe.create(name:"Sandals", category:"Footwear", url:"footwear/sandals.png")

Outfit.create(name: "Couch Potato", user: user_1, clothes:[gucci_rose, shorts ,adidas])
Outfit.create(name: "Pugtato Rulez", user: user_2, clothes:[pugtato, plaid_skirt, long_docs])
Outfit.create(name: "Power Suit", user: user_1, clothes:[pug_life, belt_skirt, docs])
Outfit.create(name: "Boy's Get Up", user: user_2, clothes:[white_button_up, khaki_cuff, dress_shoes])

# ClotheOutfit.create(clothe_id: 7, outfit_id: 1)
# ClotheOutfit.create(clothe_id: 10, outfit_id: 1)
# ClotheOutfit.create(clothe_id: 1, outfit_id: 2)
# ClotheOutfit.create(clothe_id: 10, outfit_id: 2)
# ClotheOutfit.create(clothe_id: 3, outfit_id: 3)
# ClotheOutfit.create(clothe_id: 5, outfit_id: 3)
# ClotheOutfit.create(clothe_id: 4, outfit_id: 4)
# ClotheOutfit.create(clothe_id: 9, outfit_id: 4)
#
UserClothe.create(user_id: 2, clothe_id: 2)
UserClothe.create(user_id: 1, clothe_id: 4)
UserClothe.create(user_id: 1, clothe_id: 5)
UserClothe.create(user_id: 3, clothe_id: 8)
UserClothe.create(user_id: 2, clothe_id: 10)
UserClothe.create(user_id: 4, clothe_id: 10)
